Public Class RefET_Cols
    Public Property Sno As Int32
    Public Property Date_ As DateTime
    Public Property StdTime As Decimal
    Public Property Tmid As Double
    Public Property DOY As Int16
    Public Property AirTemp As Double
    Public Property RH As Double
    Public Property Rs As Double
    Public Property wind__spd As Double
    Public Property Sc As Double
    Public Property omega As Double
    Public Property dr As Double
    Public Property delta__vapor As Double
    Public Property delta__angle As Double
    Public Property phi As Double
    Public Property beta As Double
    Public Property omega__s As Double
    Public Property omega__1 As Double
    Public Property omega__2 As Double
    Public Property Ra As Double
    Public Property Rso As Double
    Public Property fcd As Double
    Public Property TKhr As Double
    Public Property es As Double
    Public Property ea As Double
    Public Property Rnl As Double
    Public Property Rns As Double
    Public Property G As Double
    Public Property P As Double
    Public Property gamma As Double
    Public Property u2 As Double
    Public Property Cn As Double
    Public Property Cd As Double
    Public Property Rn As Double
    Public Property fcd_adv As Double
    Public Property Rs_Rso_adv As Double
    Public Property Kd As Double
    Public Property Kb As Double
    Public Property Rso_adv As Double
    Public Property W As Double
    Public Property sin_phi As Double
    Public Property ETo As Double
    Public Property ETr As Double

    Public Property int_RefET_Cols As Integer
    Public Property int_Sno As Integer
    Public Property int_StdTime As Integer
    Public Property int_Tmid As Integer
    Public Property int_DOY As Integer
    Public Property int_AirTemp As Integer
    Public Property int_RH As Integer
    Public Property int_Rs As Integer
    Public Property int_wind__spd As Integer
    Public Property int_Sc As Integer
    Public Property int_omega As Integer
    Public Property int_dr As Integer
    Public Property int_delta__vapor As Integer
    Public Property int_delta__angle As Integer
    Public Property int_phi As Integer
    Public Property int_beta As Integer
    Public Property int_omega__s As Integer
    Public Property int_omega__1 As Integer
    Public Property int_omega__2 As Integer
    Public Property int_Ra As Integer
    Public Property int_Rso As Integer
    Public Property int_fcd As Integer
    Public Property int_TKhr As Integer
    Public Property int_es As Integer
    Public Property int_ea As Integer
    Public Property int_Rnl As Integer
    Public Property int_Rns As Integer
    Public Property int_G As Integer
    Public Property int_P As Integer
    Public Property int_gamma As Integer
    Public Property int_u2 As Integer
    Public Property int_Cn As Integer
    Public Property int_Cd As Integer
    Public Property int_Rn As Integer
    Public Property int_fcd_adv As Integer
    Public Property int_Rs_Rso_adv As Integer
    Public Property int_Kd As Integer
    Public Property int_Kb As Integer
    Public Property int_Rso_adv As Integer
    Public Property int_W As Integer
    Public Property int_sin_phi As Integer
    Public Property int_ETo As Integer
    Public Property int_ETr As Integer



End Class
