'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ref_ET_Table
    Public Property ID As Long
    Public Property [Date] As String
    Public Property StdTime As String
    Public Property Tmid As String
    Public Property DOY As String
    Public Property AirTemp As String
    Public Property RH As String
    Public Property Rs As String
    Public Property wind__spd As String
    Public Property Sc As String
    Public Property omega As String
    Public Property dr As String
    Public Property delta__vapor As String
    Public Property delta__angle As String
    Public Property phi As String
    Public Property beta As String
    Public Property omega__s As String
    Public Property omega__1 As String
    Public Property omega__2 As String
    Public Property Ra As String
    Public Property Rso As String
    Public Property fcd As String
    Public Property TKhr As String
    Public Property es As String
    Public Property ea As String
    Public Property Rnl As String
    Public Property Rns As String
    Public Property G As String
    Public Property P As String
    Public Property gamma As String
    Public Property u2 As String
    Public Property Cn As String
    Public Property Cd As String
    Public Property Rn As String
    Public Property fcd_adv As String
    Public Property Rs_Rso_adv As String
    Public Property Kd As String
    Public Property Kb As String
    Public Property Rso_adv As String
    Public Property W As String
    Public Property sin_phi As String
    Public Property ETo As String
    Public Property ETr As String

End Class
