'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SIDS_GUI_Parameters
    Public Property ID As Long
    Public Property RefET_hourly_CSV As String
    Public Property SMD_daily_CSV As String
    Public Property EB_MS_Tiff As String
    Public Property EB_Thermal_Tiff As String
    Public Property Kcb_MS_Tiff As String
    Public Property SoilDepth_1 As String
    Public Property SoilDepth_2 As String
    Public Property SoilDepth_3 As String
    Public Property SoilDepth_4 As String
    Public Property SoilDepth_5 As String
    Public Property Min_Root_Depth As String
    Public Property Max_Root_Depth As String
    Public Property TAW_1 As String
    Public Property TAW_2 As String
    Public Property TAW_3 As String
    Public Property TAW_4 As String
    Public Property TAW_5 As String
    Public Property Plant_Date As String
    Public Property Harvest_Date As String
    Public Property Latitude As String
    Public Property Longitude As String
    Public Property Elevation As String
    Public Property T_Air_H As String
    Public Property W_Spd_H As String
    Public Property Longitude_Centere As String
    Public Property Site_Name As String
    Public Property Site_Summary As String
    Public Property MAD As String
    Public Property CN_Number As String
    Public Property Irrig_Efficiency As String
    Public Property EB_Tair As String
    Public Property EB_WindSpd As String
    Public Property EB_Ra As String
    Public Property EB_RH As String
    Public Property EB_WindDir As String
    Public Property EB_Date As String
    Public Property EB_StdTime As String
    Public Property Sigmoid_a_8214 As Nullable(Of Decimal)
    Public Property Sigmoid_b_8214 As Nullable(Of Decimal)
    Public Property Sigmoid_c_8214 As Nullable(Of Decimal)
    Public Property Sigmoid_d_8214 As Nullable(Of Decimal)
    Public Property Sigmoid_a_9110 As Nullable(Of Decimal)
    Public Property Sigmoid_b_9110 As Nullable(Of Decimal)
    Public Property Sigmoid_c_9110 As Nullable(Of Decimal)
    Public Property Sigmoid_d_9110 As Nullable(Of Decimal)
    Public Property Sigmoid_a_9308 As Nullable(Of Decimal)
    Public Property Sigmoid_b_9308 As Nullable(Of Decimal)
    Public Property Sigmoid_c_9308 As Nullable(Of Decimal)
    Public Property Sigmoid_d_9308 As Nullable(Of Decimal)

End Class
