'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SMD_Daily
    Public Property SNo As Long
    Public Property [Date] As String
    Public Property DOY As Nullable(Of Decimal)
    Public Property Precip As Nullable(Of Decimal)
    Public Property Surface__Runoff As Nullable(Of Decimal)
    Public Property Eff__Precip As Nullable(Of Decimal)
    Public Property Irrig As Nullable(Of Decimal)
    Public Property Eff__Irrig As Nullable(Of Decimal)
    Public Property Tmax As Nullable(Of Decimal)
    Public Property Tmin As Nullable(Of Decimal)
    Public Property ETr As Nullable(Of Decimal)
    Public Property GDD As Nullable(Of Decimal)
    Public Property Kc As Nullable(Of Decimal)
    Public Property ETc As Nullable(Of Decimal)
    Public Property Drz As Nullable(Of Decimal)
    Public Property Dmax As Nullable(Of Decimal)
    Public Property DP As Nullable(Of Decimal)
    Public Property Di As Nullable(Of Decimal)

End Class
