'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SIDSS_Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SIDSS_Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Ref_ET_Table() As DbSet(Of Ref_ET_Table)
    Public Overridable Property SIDS_GUI_Parameters() As DbSet(Of SIDS_GUI_Parameters)
    Public Overridable Property Site_Info_Summary() As DbSet(Of Site_Info_Summary)
    Public Overridable Property SMD_Daily() As DbSet(Of SMD_Daily)

End Class
