'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Site_Info_Summary
    Public Property SNo As Long
    Public Property SiteName As String
    Public Property Latitude As Nullable(Of Decimal)
    Public Property Longitude As Nullable(Of Decimal)
    Public Property Center_Longi As Nullable(Of Decimal)
    Public Property Elevation As Nullable(Of Decimal)
    Public Property Z__t As Nullable(Of Decimal)
    Public Property Z__u As Nullable(Of Decimal)
    Public Property Summary As String

End Class
